### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by Alhadis** [Alhadis/Print#1]
Remaining tasks
----------------------

* [ ] Write documentation (obviously)
* [ ] Show named properties in `Map` and `Set` objects:

	```js
	let s = new Set([ "A" ]);
	s.custom = "property"; // Not listed
	```
* [ ] Additional method to generate SGR-coloured output (`print.withSGR(...);`...?)
